name: 'Cloudflare Purge Cache Action'
description: 'Purges cache on a cloudflare zone'
author: 'GitHub'
inputs:
  authToken:
    description: 'Your Cloudflare auth token'
  zoneName:
    description: 'The zone you wish to purge'

runs:
  using: 'docker'
  image: 'Dockerfile'